const LOAD_DATA = 'LOAD_DATA'
const UPDATE_DATA = 'UPDATE_DATA'
const SAVE_DATA = 'SAVE_DATA'
const SWITCH_TODOLIST = 'SWITCH_TODOLIST'
const ADD_TODOLIST = 'ADD_TODOLIST'
const ADD_TODOITEM = 'ADD_TODOITEM'
const DELETE_TODOLIST = 'DELETE_TODOLIST'
const DELETE_TODOITEM = 'DELETE_TODOITEM'

export { 
  LOAD_DATA, 
  UPDATE_DATA,
  SAVE_DATA,
  SWITCH_TODOLIST,
  ADD_TODOLIST,
  ADD_TODOITEM,
  DELETE_TODOLIST,
  DELETE_TODOITEM,
}