const LOAD_DATA = 'LOAD_DATA'
const UPDATE_DATA = 'UPDATE_DATA'
const SAVE_DATA = 'SAVE_DATA'
const SWITCH_TODOLIST = 'SWITCH_TODOLIST'
const ADD_TODOLIST = 'ADD_TODOLIST'
const ADD_TODOITEM = 'ADD_TODOITEM'

export { 
  LOAD_DATA, 
  UPDATE_DATA,
  SAVE_DATA,
  SWITCH_TODOLIST,
  ADD_TODOLIST,
  ADD_TODOITEM
}